Improve admin panel
doofinder/doofinder-prestashop pull request #120
Opened 2023-03-30 09:25 UTC by frobs

Required by #80

2023-03-30 11:46 UTC, ivan-doofinder requested changes

2023-03-30 11:46 UTC, ivan-doofinder commented on views/templates/admin/configure_administration_panel.tpl
> +          <p style="font-size: 1.1em;">Accede al panel de Doofinder y descubre todas las funcionalidades para aumentar tus ventas.</p>
These texts must be translated

2023-03-30 11:46 UTC, ivan-doofinder commented on views/templates/admin/configure_administration_panel.tpl
> +            Ir al panel de Doofinder
Same

2023-03-30 11:46 UTC, ivan-doofinder commented on doofinder.php
> +        (empty($isMobile) && $displayDesktop)) {
```suggestion
        if (getDisplayLayer())
```
Maybe it's something confusing. Better to create a function that contains the logic of whether to show the layer, and in the IF here just call that function.
In addition, the function can be used for other cases

2023-03-30 11:46 UTC, ivan-doofinder commented on doofinder.php
> +        $fields['DF_SHOW_LAYER_MOBILE'] = $this->getShowLayerMobileConfig();
```suggestion
        $fields['DF_SHOW_LAYER'] = Configuration::get('DF_SHOW_LAYER', true);
        $fields['DF_SHOW_LAYER_MOBILE'] = Configuration::get('DF_SHOW_LAYER_MOBILE', true);
```
Why call an intermediate function if you can get the values directly?

2023-03-31 10:00 UTC, albertodoofinder approved these changes

2023-03-31 10:19 UTC, ivan-doofinder requested changes

2023-03-31 10:19 UTC, ivan-doofinder commented on doofinder.php
> +        (empty($isMobile) && $displayDesktop);
```suggestion
        return ($isMobile && $displayMobile) || (!$isMobile && $displayDesktop);
```
I think this is more readable

2023-03-31 12:37 UTC, mdogo approved these changes

2023-04-03 07:27 UTC, ivan-doofinder approved these changes

2023-04-03 10:56 UTC, merged