Unplugged 309 | not activate layer until indexing completed
doofinder/doofinder-prestashop pull request #124
Opened 2023-04-12 04:34 UTC by frobs

Required by [#309](https://github.com/doofinder/dfcommon/issues/309)

2023-04-14 09:14 UTC, albertodoofinder approved these changes

2023-04-14 10:55 UTC, ivan-doofinder requested changes

2023-04-14 10:55 UTC, ivan-doofinder commented on controllers/front/callback.php
> +            header('Access-Control-Allow-Headers: x-requested-with, Content-Type, origin, authorization, accept, client-security-token');
Es necesario el envío de estas cabeceras?

2023-04-14 10:55 UTC, ivan-doofinder commented on controllers/admin/DoofinderAdminController.php
> +        }
No es necesario. El displayAjax ya se encarga de comprobar la acción.

2023-04-14 10:55 UTC, ivan-doofinder commented on controllers/front/callback.php
> +        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
Es un endpoint abierto a "todo el mundo", que no se está realizando ninguna comprobación de seguridad. El impacto es casi nulo, pero en un caso como este que hay modificación sobre base de datos habría que aplicar alguna medida.
Como sugerencias:
- Generar la URL de callback con un token único y luego aquí comprobar ese token
- Aceptar solo peticiones del dominio de Doofinder

2023-04-14 11:02 UTC, ivan-doofinder requested changes

2023-04-14 11:02 UTC, ivan-doofinder commented on doofinder.php
> +        $store_data['callback_urls'] = $callbacksUrls;
Aquí tengo dudas. Para cada search engine se envía un callback_url. Por lo tanto vamos a recibir al endpoint una llamada cada vez que un search engine se ha indexado.
Pero el control que estamos haciendo es de poner DF_FEED_INDEXED a TRUE cuando nos llegue el primero de los callbacks. Por lo que si tenemos 20 SE en una store, cuando indexe el primero de ellos ya vamos a marcar como que está indexado (se quita el mensaje de indexación).
¿Es correcto así?

2023-04-14 11:11 UTC, ivan-doofinder commented
Me he descargado la rama para probar. Una vez instalo y se indexa, el mensaje de indexación en progreso no desaparece. Es necesario recargar la página para dejar de ver ese mensaje. Seguramente producto quiera que el mensaje no se quede ahí de forma permanente.

2023-04-14 11:17 UTC, frobs commented on controllers/front/callback.php
> +            header('Access-Control-Allow-Headers: x-requested-with, Content-Type, origin, authorization, accept, client-security-token');
En realidad solo la de Access-Control-Allow-Origin para controlar que las peticiones vienen de doofinder.com, Elimino el resto.

2023-04-14 11:18 UTC, frobs commented on controllers/front/callback.php
> +        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
He añadido control por dominio que hace la petición a través de la cabecera Access-Control-Allow-Origin

2023-04-14 11:21 UTC, frobs commented on controllers/admin/DoofinderAdminController.php
> +        }
Eliminado.

2023-04-14 12:49 UTC, frobs commented on doofinder.php
> +        $store_data['callback_urls'] = $callbacksUrls;
He confirmado el comportamiento con Cristobal y me ha dicho que así está bien, si surge algún problema ya vemos

2023-04-17 07:54 UTC, albertodoofinder approved these changes

2023-04-17 09:48 UTC, ivan-doofinder approved these changes

2023-04-17 09:50 UTC, albertodoofinder approved these changes

2023-04-17 10:36 UTC, mdogo approved these changes

2023-04-17 10:39 UTC, merged