Unique Script
doofinder/doofinder-prestashop pull request #216
Opened 2024-05-23 14:38 UTC by eduardogomez97

Required by: https://github.com/doofinder/doofinder-prestashop/issues/211

2024-05-23 15:16 UTC, pedromcp90 approved these changes

2024-05-23 15:29 UTC, sofia-doofinder requested changes

2024-05-23 15:29 UTC, sofia-doofinder commented on doofinder.php
> -    const VERSION = '4.7.34';
@eduardogomez97 creo que había dos ficheros con la capa no? faltaría el de las versiones antiguas de prestashop? o me estoy confundiendo?

2024-05-23 15:33 UTC, davidmolinacano commented on doofinder.php
> -    const VERSION = '4.7.34';
Pero esos ficheros en realidad no tenían que ver con las versiones de Prestashop, sino que uno es de la layer V7 y otro el de la V9 si no recuerdo mal :thinking:

2024-05-23 15:33 UTC, eduardogomez97 commented on doofinder.php
> -    const VERSION = '4.7.34';
Sí, pero justo ahora lo estaba comentando con Kappa. Por que tenía la duda si este cambio era solo respecta a la v9 o para la v7 también.

2024-05-23 15:35 UTC, davidmolinacano approved these changes
LGTM! Excellent! :raised_hands: :medal_military:

2024-05-27 14:41 UTC, sofia-doofinder approved these changes

2024-05-31 15:31 UTC, sofia-doofinder commented
@eduardogomez97 & @davidmolinacano he añadido en este commit la versión en el payload a la hora de crear la store

2024-06-04 09:13 UTC, merged