Check if the update on save is apt
doofinder/doofinder-prestashop pull request #233
Opened 2024-08-21 09:51 UTC by eduardogomez97

Required by: https://github.com/doofinder/doofinder-prestashop/issues/230

2024-08-21 11:38 UTC, sofia-doofinder requested changes

2024-08-21 11:38 UTC, sofia-doofinder commented on lib/doofinder_api_search_engine.php
> +class DoofinderApiSearchEngine
el nombre en un prinicipio me ha parecido que haría las peticiones a doofAPI por el nombre de la clase. Igual se le podría ajustar un poco porque en realidad no es una API de search engines no?

2024-08-21 11:38 UTC, sofia-doofinder commented on lib/doofinder_api_search_engine.php
> +    public function apt_update_on_save($installation_id)
aquí diría como en doopluginsd e cambiar el nombre y poner algo más descriptivo, esto de apt creo que no se entiende bien no se bien que nombre pero quizás algo como `is_configuration_valid_update_on_save` o `is_valid_update_on_save` o quizás algo más concreto de lo que estamos validando `has_duplicated_indices_by_type` o no se algo por el estilo pero que explique mejor lo que queremos hacer...

2024-08-21 11:38 UTC, sofia-doofinder commented on lib/doofinder_api_search_engine.php
> +        return $this->get($api_endpoint);
aquí no sería mejor devolver ya el valor que necesitamos? me refiero a en vez de hacer todo esto después hacerlo directamente aquí 
```
      if (empty($response) || $response['status'] !== 200) {
            $this->debug('Error checking search engines: ' . json_encode($response));

            return false;
        }

        return @$response['apt?'];
```

2024-08-21 15:16 UTC, juan-gm approved these changes

2024-08-21 15:52 UTC, sofia-doofinder approved these changes

2024-08-22 12:38 UTC, sofia-doofinder commented on doofinder.php
> +        return @$decode_response['valid?'];
Edu creo que esto que mira si la respuesta es un 200 o no y devuelve el valor mejor meterlo dentro de la función `is_valid_update_on_save` de la api no? porque esta función creo que no debería entender de respuestas http, o estoy mezclando?

2024-08-22 14:16 UTC, eduardogomez97 commented on doofinder.php
> +        return @$decode_response['valid?'];
De momento se va a dejar aquí, hay que darle una vuelta a eso https://github.com/doofinder/doofinder-prestashop/issues/234

2024-08-26 07:44 UTC, merged