PSN-513 | Call create store endpoint
doofinder/doofinder-prestashop pull request #56
Opened 2022-07-05 16:05 UTC by pedromcp90

2022-07-05 16:38 UTC, abraham-doofinder requested changes

2022-07-05 16:38 UTC, abraham-doofinder commented on doofinder.php
> +                    $feed_url = $this->getShopURL($shop['id_shop'])
You can use `$shop_name` var declared previously in line 2478 instead of `$this->getShopUrl()`

2022-07-06 07:08 UTC, alvanieto approved these changes

2022-07-06 08:08 UTC, abraham-doofinder approved these changes

2022-07-06 12:57 UTC, ivan-doofinder requested changes

2022-07-06 12:57 UTC, ivan-doofinder commented on doofinder.php
> +
```suggestion
            $primary_lang_id = Configuration::get('PS_LANG_DEFAULT', null, $shop['id_shop_group'], $shop['id_shop']);
            $primary_language_iso_code = Language::getIsoById($primary_lang_id)

```
- Add the id_shop when obtaining the language, so that it gives you the default language of the store that you indicate.
- Function Language::getIsoById gives the ISO of the language.

2022-07-06 15:18 UTC, pedromcp90 commented on doofinder.php
> +
That's great, thanks

2022-07-07 09:43 UTC, ivan-doofinder approved these changes

2022-07-07 10:16 UTC, merged