#60 Allow new store configuration
doofinder/doofinder-prestashop pull request #61
Opened 2022-07-20 10:57 UTC by pedromcp90

With this PR we add the possibility to create new stores in doofinder when the user creates a new Shop

Note:
Sorry for the indentation changes in doofinder.php, the important changes are in the following functions:
- getContent
- renderFeedURLs
- buildFeedUrl
- doofinderInShop
- autoinstaller
- createStore
- setDefaultShopConfig

2022-07-21 11:38 UTC, ivan-doofinder requested changes

2022-07-21 11:38 UTC, ivan-doofinder commented on doofinder.php
> +        $admin_endpoint = Configuration::get('DF_AI_ADMIN_ENDPOINT', null, 1, 1);
```suggestion
        $apikey = Configuration::getGlobalValue('DF_AI_APIKEY');
        $admin_endpoint = Configuration::getGlobalValue('DF_AI_ADMIN_ENDPOINT');
```

2022-07-21 11:38 UTC, ivan-doofinder commented on doofinder.php
> +        $api_endpoint = Configuration::get('DF_AI_API_ENDPOINT', null, 1, 1);
```suggestion
        $apikey = Configuration::getGlobalValue('DF_AI_APIKEY');
        $api_endpoint = Configuration::getGlobalValue('DF_AI_API_ENDPOINT');
```

2022-07-21 11:38 UTC, ivan-doofinder commented on doofinder.php
> +        $admin_endpoint = Configuration::get('DF_AI_ADMIN_ENDPOINT', null, 1, 1);
And change in line 2499 to this:
```
Configuration::updateGlobalValue('DF_AI_APIKEY', $apikey);
Configuration::updateGlobalValue('DF_AI_ADMIN_ENDPOINT', $admin_endpoint);
Configuration::updateGlobalValue('DF_AI_API_ENDPOINT', $api_endpoint);
```

2022-07-21 11:38 UTC, ivan-doofinder commented on doofinder.php
> +        //$apikey = Configuration::get('DF_API_KEY');
remove commented line

2022-07-21 11:38 UTC, ivan-doofinder commented on doofinder.php
> +    }
```suggestion
    protected function doofinderInShop($shop)
    {
        $installation_id = Configuration::get('DF_INSTALLATION_ID', null, $shop->id_shop_group,  $shop->id);
        return !empty($installation_id);
    }
```
id_category? why?

2022-07-21 11:39 UTC, ivan-doofinder commented
When running a test to create a store, it shows me this message. Can you check it?
![imagen](https://user-images.githubusercontent.com/97448277/180204853-0ba357c3-93a4-43c6-9215-33dacb12388f.png)

2022-07-21 11:50 UTC, ivan-doofinder requested changes

2022-07-21 11:50 UTC, ivan-doofinder commented on doofinder.php
> +        $this->version = '4.2.3';
```suggestion
        $this->version = '4.3.0';
```
It is a new functionality. I would put this version

2022-07-22 08:20 UTC, pedromcp90 commented on doofinder.php
> +    }
It probably was an error

2022-07-22 13:02 UTC, sofia-doofinder approved these changes

2022-07-26 11:03 UTC, ivan-doofinder approved these changes

2022-07-27 07:38 UTC, merged